<table border="1" class="ccat" style="width:100%; border: 4px solid red; border-radius:5px;">
  <thead>
    <tr style="text-align:center;"><th class="ou-help">Course Catalog URL</th></tr>
	<tr><th class="ou-help" style="text-align:left;">example: https://catalog.uark.edu/graduatecatalog/business/informationsystemsisys/</th></tr>
	<tr><th class="ou-help" style="text-align:left;">example: https://catalog.uark.edu/graduatecatalog/business/informationsystemsisys/#courseinventory</th></tr>
  </thead>
  <tbody>
    <tr>
      <td class="ccat-link" style="font-size:14px">https://catalog.uark.edu/graduatecatalog/business/informationsystemsisys/</td>
    </tr>
  </tbody>
</table>
<h3 class="wysiwyg-spacer">PRESS ENTER HERE FOR A NEW LINE-&gt;</h3>
